### ISSUE TITLE
New graphs for clade analysis:

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#114]
Hey guys,
I am working on the graphs for the permutation test,  any suggestion?

![image](https://cloud.githubusercontent.com/assets/9639481/18399303/a12267de-76a6-11e6-84fd-4744153539ca.png)

![image](https://cloud.githubusercontent.com/assets/9639481/18399332/ba6bbb96-76a6-11e6-8e48-144c98afca13.png)

**Comment by paternogbc** [comment]
Actually, I decided to include the FULL model vertical line also (black). What do you think?
![image](https://cloud.githubusercontent.com/assets/9639481/18411038/ab9a4d5e-7745-11e6-9b55-e47f1497dd69.png)

**Comment by caterinap** [comment]
Hey! They look great!
Few questions: is the red dotted line the same thing in the left/right graphs? Why in the Challitrichidae example the slope is positive in the scatterplot and negative in the histogram?
It might be better to add a legend also for the permutation graphs?


The red dotted line in the right/left graphs is not exactly the same thing and people might get confused. The black line is the median?

**Comment by gijsbertwerner** [comment]
Yes, very cool, Gustavo! I like the addition of the full black line so people can more easily compare :-)

And agreed with Caterina we should very clearly explain in the function details (or in the figure) what precisely the lines refer to to avoid confusion.

No suggestions otherwise :-)

-----------------------------------------
Dr. Gijsbert Werner
Newton Fellow
Department of Zoology
University of Oxford
South Parks Road
Oxford
OX1 3PS
United Kingdom




On 10 Sep 2016, at 15:00, Gustavo Paterno <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually, I decided to include the FULL model vertical line also (black). What do you think?
[image]<https://cloud.githubusercontent.com/assets/9639481/18411038/ab9a4d5e-7745-11e6-9b55-e47f1497dd69.png>

**Comment by caterinap** [comment]
Oh yeah, the black line is not the median, it's the full model. Sorry, next time I'll read better :)

**Comment by paternogbc** [comment]
Sorry Guys!
I did not mention. The black and red lines are the same on both graphs =)) 

So you can see if there is an increase or decrease in slope on both graphs but compare with the NULL simulations on the right histogram..
