### ISSUE TITLE
set of trees: Let the user provide a set of tree

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#122]
We also need to adress this point. Let the user provide a set of good trees instead of just randomizing between all possibles. It is important to think this before starting everything else, specially bcause this will affect all functions related to tree_uncertainty.

Any suggestions?

**Comment by gijsbertwerner** [comment]
I presume you mean this in relation to the reviewer 1 comments at lines 122-124? What if users have a set of trees and know that some of these are 'better' than others, for instance because they have bootstrap support values? 

I suppose I agree that in a way it is not optimal to treat all potential trees from a set as equally likely, which I guess is what we are doing now. A relatively straightforward around this would be to rather than iterating over all the trees in the set, randomly select trees for each iteration with the likelihood of selection being dependent on some weighing factor. The weighing factor could for instance be bootstrap support value or some other (subjective) measure the user specifies. 

If we are going to go down this path, I suppose it would change quite a bit how tree_ work, practically and conceptually. It would probably be an improvement, over the current because it gives user more flexibility (they can always recover the current default by setting all weights equal), but it would be quite some change. Certainly we should do it before implementing all the interactions things, if at all. 

Do you think wise to do something like this at this stage?

**Comment by caterinap** [comment]
It's not too complicated to sample based on a given weight but we need to think it well so we don't slow down the function too much.

**Comment by paternogbc** [comment]
I was thinking on a different comment.
> "Phylogenetic uncertainty, for example, can be a concern in the same time we want to evaluate the effect of a given clade on the parameter estimates of the model. With the current tools I can imagine a loop over n trees and check the output of 'tree_phylm' or 'tree_phyglm' independently n times. However, I think this step could be simplified by enabling the user to provide a list of trees for each of the functions in the package. This would be of especial interest for researchers focusing on results of Bayesian tree estimation, since it is common to integrate parameter estimates from comparative models over a sample of trees from the posterior distribution."

The idea of weighting trees while sampling is quite nice. But I think his suggestion is on the direction of the interaction bwtween uncertainties. So I think the tree_inter would do the job. Do you agree? because as I understood beteer now, I think he was suggesting to allow the user to provide a list of trees for the other functions instead of just one. So, for influ_xxx the function would loop along the trees if a list is provided and repeat the influ analysis for each tree (this is what we pretend to do with the interaction between tree and influ).

**Comment by gijsbertwerner** [comment]
Ah, I think I now see what you mean, Gustavo. Yes, I suppose that with the ideas we discussed this morning and on planning on doing, we are effectively doing this (allowing the user to test parameter values for influ/clade etc) across a set of trees? Sounds good to me! 

Let's keep the idea of assigning weighing factors to sets of trees in mind for future versions for now, I suppose. Seems not key for this version, and will probably slow us (and the function) down quite a bit. We can keep the idea as a future enhancement idea?

**Comment by paternogbc** [comment]
Yep, that is exactly what I think! 
It was a bit confusing but now is clear to me. By interactions he was focusing on phylogenetic uncertainty interacting with the others uncertainties. 

And yes lets keep the idea of weighting the trees for the next version. It should be easy to implement as Cat pointed. And a quite nice feature.

**Comment by paternogbc** [comment]
We could also consider this approach.

When `times = "all"` we could run the analysis for all trees provided by the user. (the set of selected trees).
This might easily help users who has a set of "good" trees that they want to average the parameters estimation. 

So when the user sets times = "all" then, 

`  trees <- 1:length(phy)`

instead of choosing a random set of trees 

` trees <- sample(length(phy), times, replace = F)`

I will implement this change in `tree_physig` and we could think to use it also in the other functions with phylogenetic uncertainty. What do you think @caterinap ?

I would actually leave as the default behavior of times = "all".

**Comment by caterinap** [comment]
I think it's a good idea. I am just worried that if it's the default, people will think it's the best option. And if someone has 1000 trees it can be problematic (that's why we chose 2 as default). One possibility would be to ask for a confirmation if times>50 (for example) but this can be problematic when people parallelize or use the function within a loop..

**Comment by paternogbc** [comment]
Ok Great. We could just add the "all" functionality if the user wants to run to all trees and we simple 
add this bit of code to the function:
```
if (times == "all"){
times <- length(phy)
} 
```
And dont change the ``` trees <- sample(length(phy), times, replace = F)``` code.
This would just ensure that all trees are evaluated without much change =)
