### ISSUE TITLE
Bug: match_dataphy() different species names order on multiphylo

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#129]
The function `math_dataphy()` can deal with 'phylo' or 'multiphylo' files. 
How ever, when a 'multiphylo' files is provided it is necessary to consider that different trees might have different order of species names and crop each tree accordingly. Otherwise, the croped 'multiphylo' will show the wrong species names for different trees. 
Plus, the order of species on the output phylogeny and data must be the same so they not only 
check for the intersect between data and phy but also match both at the same order.

Is that correct @caterinap ?
This should be easy to fix.

You can check the problem with the following code:
```
library(sensiPhy)

# Load data:
data(alien)
head(alien$data)
# Match data and phy based on model formula:
comp.data <- match_dataphy(gestaLen ~ adultMass, data = alien$data, alien$phy)

# First tree:
# Number of names in the same order:
sum(rownames(comp.data$data) == comp.data$phy$STATE_200000$tip.label)
# Number of names in data that intersect with tree
length(intersect(rownames(comp.data$data), comp.data$phy$STATE_200000$tip.label))

# Second tree:
# Number of names in the same order:
sum(rownames(comp.data$data) == comp.data$phy$STATE_400000$tip.label)
# Number of names in data that intersect with tree
length(intersect(rownames(comp.data$data), comp.data$phy$STATE_400000$tip.label))
```

In the first example data and tree match the order of species while in the second tree they dont.

**Comment by caterinap** [comment]
Hey I am back! (finally!).
Yes, you are right! I am working to fix this. Thanks!

**Comment by paternogbc** [comment]
great Cat! =))

**Comment by caterinap** [comment]
We cannot reorder the tree tips without changing the tree structure so we need to create a list of dataframes (instead of only one), with every dataset matching the tip order of each tree in the `multiphylo`. We can do this either:
- in the `match_dataphy` function itself, in this case if the input is a `multiphylo` the function returns a list of datasets matching tip.names of each multiphylo tree and we just need to handle this in the _tree_ functions
- change `match_dataphy` so it only works with `phylo `objects and apply `match_dataphy`to all trees in the _tree_ functions.
I am going for the first option (I think it might interest people to use this functionality) and will need to slightly change all _tree_ functions + interactions. Unless you see any problem with this approach.

**Comment by paternogbc** [comment]
Hey Cat! You are right! Nice ;)

What about just reordering the dataset always accordingly to the tree in all functions.
So we keep the match_dataphy as it is, but always re-order the dataset on every different tree it is used inside all functions in the package?

We could create a small function that does this, get the number of tree being analysed, then re-order the dataset rows to match that specific tree. Then this function could go before running functions that require 'multiphylo' on each tree interaction.

With this we might avoid big changes on the other functions besides adding one function to (match the order of the specific tree with the dataset). If we decide this, it would be handy to tell people that just the first tree is in the same order with the data, because it is impossible to re-order species name in the tree. 

But I am also good with the first option =) 
Your call =)

Cheers,
Guga

**Comment by caterinap** [comment]
Mmh so you would use match_data_phy only to remove NAs and prune tree/data to the common species names (and thus remove from the function the bit on re-ordering). And you would have a separate function to reorder species names in the datasets, that we would use just before phylm ?

**Comment by paternogbc** [comment]
Yes, that is what I was thinking. The function can run before each iteration with different trees.
On the non-tree functions this problem wont be present right, because there is only one tree and
the species list on the data is ordered given the only phylogeny available.

Following the example I gave, you could try something like the function below `ord_dataphy`

```
library(sensiPhy)

# Load data:
data(alien)
# Match data and phy based on model formula:
comp.data <- match_dataphy(gestaLen ~ adultMass, data = alien$data, alien$phy)

### Test tree number 3 match data
n.phy <- 3
### Number of species that matach data and phy
sum(rownames(comp.data$data) %in% comp.data$phy[[n.phy]]$tip.label)
### Number of species in the same order in data and phy
sum(rownames(comp.data$data) == comp.data$phy[[n.phy]]$tip.label)

### Function to re-order data rows given a specific tree in compartive dataset:
ord_dataphy <- function(x, n.phy){
  ord <- match(x$phy[[n.phy]]$tip.label, rownames(x$data))
  x$data <- x$data[ord, ]
  x$phy <- x$phy[[n.phy]]
  return(x)
}

## Example:
a <- ord_dataphy(x = comp.data, n.phy = 3)

### Number of species that matach data and phy
sum(rownames(a$data) %in% a$phy$tip.label)
### Number of species in the same order in data and phy
sum(rownames(a$data) == a$phy$tip.label)
```

**Comment by caterinap** [comment]
ok, yes, sound better to have it in the loop than creating an heavy list of datasets beforehand. And if in future we see an interest in putting it back in `match_data_phy `we can still do it.

**Comment by paternogbc** [comment]
Yep! Perfect. I think, we could add on the details of match_dataphy() that when 'multiphylo' is provided the data species order will only match the first phylogeny and the others wont follow the order. 
So people can still use the function to crop multiple trees. And later we see what is the best approach to include that inside the function. =) Super, lets go hahaha

**Comment by caterinap** [comment]
We can go two ways: 
1- add Gustavo's `ord_dataphy` to utils.R and use it in the tree loop
2- or since data is already matched using `match_data_phy` but just needs to be reordered, add one line at the beginning of the tree loop, e.g.:
 `full.data <- full.data[phy[[j]]$tip.label,]`
Let me know if you have a preference and I'll do it :)
The main interest of approach 1 is if people have trees with different species names/numbers in their multiphylo. Is that a possible scenario? If yes we should rather build a `match_data_phy` version for multiphylo only (`ord_dataphy` alone would not be enough).

**Comment by paternogbc** [comment]
Hey Cat,

I am fine with both approaches, but perhaps number 2 is faster.
And yes it is possible to have different trees in the multiphylo file.
We might check this inside `match_dataphy` and avoid this problem. Just check if all trees has the same number and species before start matching.

**Comment by gijsbertwerner** [comment]
I would go for the second option, since it’s easier and faster. I suppose it’s not entirely unheard of that people have different species numbers/names in multiphylo objects, but typically that won’t be the case (because these are usually for things like bootstrap replicates). If we specific that all need to include same species set, and throw a warning if they don’t it should be fine that we don’t accommodate those few people having other numbers of species.

---------------------------------------------------
Dr. Gijsbert Werner
Newton Fellow, Department of Zoology
Junior Research Fellow, Balliol College
University of Oxford

Balliol College
Broad Street
Oxford
OX1 3BJ
United Kingdom



On 12 May 2017, at 09:14, Gustavo Paterno <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Cat,

I am fine with both approaches, but perhaps number 2 is faster.
And yes it is possible to have different trees in the multiphylo file.
We might check this inside match_dataphy and avoid this problem. Just check if all trees has the same number and species before start matching.

**Comment by caterinap** [comment]
Ok perfect! Let's go for solution 2 and maybe implement solution 1 in future. (just that you know and we don't do double work, I am working on a "interactions_tree" branch and started with intra_tree)

**Comment by gijsbertwerner** [comment]
Perfect! I will only have time to return some coding next week anyway, so will not touch any of this for now :-) Sounds really good!

---------------------------------------------------
Dr. Gijsbert Werner
Newton Fellow, Department of Zoology
Junior Research Fellow, Balliol College
University of Oxford

Balliol College
Broad Street
Oxford
OX1 3BJ
United Kingdom



On 12 May 2017, at 09:36, Caterina Penone <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok perfect! Let's go for solution 2 and maybe implement solution 1 in future. (just that you know and we don't do double work, I am working on a "interactions_tree" branch and started with intra_tree)

**Comment by paternogbc** [comment]
Just to fix, there was a error on the ord_datphy() function. The correct function is:

```
### Function to re-order data rows given a specific tree in compartive dataset:
ord_dataphy <- function(x, n.phy){
  ord <- match(x$phy[[n.phy]]$tip.label, rownames(x$data))
  res <- list(data = x$data[ord, ],
              phy = x$phy[[n.phy]])
  return(res)
}
```
