### ISSUE TITLE
Help Checking

### ISSUE THREAD

**Issue by gijsbertwerner** [paternogbc/sensiPhy#152]
Have created a branch help_check to do this. Just for our own recored & peace of mind, a list of the ones that I have already checked (updating this all the time I do one):

- clade_phylm (only minor textual changes, help examples all work)
- clade_phyglm (only minor textual changes, help examples all work)
- intra_clade_phylm (minor textual changes, reduced number of sims in example, help examples mostly work but plotting issue)
- intra_clade_phyglm (minor textual changes, reduced number of sims in example, help examples mostly work but plotting issue)
- tree_clade_phylm (minor textual changes, reduced number of sims in example, help examples mostly work but plotting issue)
- tree_clade_phyglm (minor textual changes, reduced number of sims in example, help examples mostly work but plotting issue)

**Comment by gijsbertwerner** [comment]
Some issues still to fix that I noted during help-function testing. 

- For sensiplot(intra_clade) I get the error message `Error in multiplot(g.out, g2, cols = 2) : 
  could not find function "multiplot"`. Could be some ggplot version thing?

**Comment by paternogbc** [comment]
Hey @gijsbertwerner, that is very nice =) thanks!

regarding the "multiplot", this is a function I included on the script: utils_plot.R to gather multiple ggplots in one single plot. Because this functions is not exported in the package, some time if you run the function code "by hand" instead of building the package it wont find "multiplot" because this function only works within the package. It is a bit confusing sorry. Try to make a change and rebuilt the package, if the problem does not go away let me know I will try to find out. Maybe you can report here any other problem you find, I think this workflow is good to catch minor issues and track then down.

**Comment by gijsbertwerner** [comment]
Hey @paternogbc . Great this makes sense! I had something similar with summary(x) fort both both `"sensiTree_Clade"` and `"sensiIntra_Clade" `. Manually running the internal functions in utils_plot.R and in summary_methods.R solves this and then everything works great. So I think you are right that it will be some building thing. Let's carefully check that again at the end, I suppose most practical?

**Comment by paternogbc** [comment]
Hey @gijsbertwerner great! 
Yep we can check, but if the re-build fixed, it is all good. Is just that you mask the original function when you run the code by hand. Then, the new function is set at the global environment. But in th global environment, there is no multiplot, because this function was not exported from the package =)

**Comment by caterinap** [comment]
Are the plotting issues only linked to the multiplot or is there something else?

**Comment by paternogbc** [comment]
Hey @caterinap ,

could you check this example with i`ntra_phylm`, I think something went wrong with the plot.

```
# Load data:
data(alien)
# run PGLS accounting for intraspecific variation:
intra <- intra_phylm(gestaLen ~ adultMass, y.transf = log, x.transf = log, 
                     phy = alien$phy[[1]], data = alien$data, Vy = "SD_gesta", n.intra = 30)
# To check summary results:
summary(intra)
# Visual diagnostics
sensi_plot(intra)
```

![image](https://user-images.githubusercontent.com/9639481/28707691-99787778-7379-11e7-847e-70d127566e76.png)

The regression line looks wrong.

**Comment by caterinap** [comment]
It's linked to the transformations, data is raw and lines is from log. I'll fix that.

**Comment by paternogbc** [comment]
@caterinap perfect!
