### ISSUE TITLE
tree_bd: new function for diversification rate

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#170]
Hey guys,

just pushed a new function `tree_bd()` to the branch https://github.com/paternogbc/sensiPhy/tree/new_div_rate

It implements tree_ method for net diversification rate (Magallon and Sanderson, 2000) and speciation rate (Kendall-Moran). 

For `sensi_plot()` I tried to follow the same simple graphs for showing the distribution of estimates across different trees. Let me know what you think =)  
As we discussed before, diversification rates dont vary much between trees. 
![image](https://user-images.githubusercontent.com/9639481/33236295-3110bae0-d2a3-11e7-8db7-8733762646e1.png)

**Comment by gijsbertwerner** [comment]
Looks great, Gustavo! Thanks :-)

---------------------------------------------------
Dr. Gijsbert Werner
Newton Fellow, Department of Zoology
Junior Research Fellow, Balliol College
University of Oxford

Balliol College
Broad Street
Oxford
OX1 3BJ
United Kingdom




On 26 Nov 2017, at 01:17, Gustavo Paterno <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey guys,

just pushed a new function tree_bd() to the branch [https://github.com/paternogbc/sensiPhy/tree/new_div_rate].

It implements tree_ method for net diversification rate (Magallon and Sanderson, 2000) and speciation rate (Kendall-Moran).

For sensi_plot() I tried to follow the same simple graphs for showing the distribution of estimates across different trees. Let me know what you think =)
As we discussed before, diversification rates dont vary much between trees.
[image]<https://user-images.githubusercontent.com/9639481/33236295-3110bae0-d2a3-11e7-8db7-8733762646e1.png>

**Comment by gijsbertwerner** [comment]
Sorry, but I have only had the chance to look into this a bit closer and check your implementations.

Seem to all work great to me, Gustavo :-)

Quite interesting that if you execute the examples the Kendall-Moran methods seems to be a bit more affect than Magallon. Might be nice to use that one in tutorial.

One small remarks For me the models only work if I use ‘phy = primates$phy’ rather than the example ‘pay = primates.phy’. Perhaps this has to do with the dataset issue from #167. I haven’t changed anything, because wanted to figure that out first, but thought I’d highlight.

---------------------------------------------------
Dr. Gijsbert Werner
Newton Fellow, Department of Zoology
Junior Research Fellow, Balliol College
University of Oxford

Balliol College
Broad Street
Oxford
OX1 3BJ
United Kingdom



On 26 Nov 2017, at 01:17, Gustavo Paterno <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey guys,

just pushed a new function tree_bd() to the branch [https://github.com/paternogbc/sensiPhy/tree/new_div_rate].

It implements tree_ method for net diversification rate (Magallon and Sanderson, 2000) and speciation rate (Kendall-Moran).

For sensi_plot() I tried to follow the same simple graphs for showing the distribution of estimates across different trees. Let me know what you think =)
As we discussed before, diversification rates dont vary much between trees.
[image]<https://user-images.githubusercontent.com/9639481/33236295-3110bae0-d2a3-11e7-8db7-8733762646e1.png>

**Comment by paternogbc** [comment]
That is interesting, KM varies much more (I will update that for the example). Thanks!

@gijsbertwerner regarding the data problem I am also not sure how to deal with. 
In my computer phy = primates.phy" works fine... I will do some other tests and see if I have any idea about it. Thanks for spotting.
