### ISSUE TITLE
NA's in data

### ISSUE THREAD

**Issue by caterinap** [paternogbc/sensiPhy#37]
Hi,
I added the function that matches names in phylogeny and traits.
Phylolm does not deal with NA's so in my previous scripts I removed the species with NA's in response or predictor. But just NA's in those two columns, not the others. For example I was allowing the dataset to have an NA in the column containing info on trait variability, in that case I replaced NA with a zero when randomly selecting a value in the interval. So I think this is useful but I do not see any more elegant way to do that than asking the user to give the name of the response and predictor... Any thoughts?

**Comment by caterinap** [comment]
Ok, maybe ask the user to already put the formula they are going to use might solve the problem..?

**Comment by paternogbc** [comment]
I would say that this functions needs the argument (formula). Because the user wont use the crop.na function itself, when he sets samp_phylolm (formula, ...) this will be passed to the crop.na function. 
What do you think?

So, I dont think we need to export this function, is just a internal. You might save this in a new file, called utilities.R , just add the function there, no documentation from roxygen. Then you can call this function inside the others. =)

**Comment by caterinap** [comment]
Yep, good thought, thanks!
