### ISSUE TITLE
Plot with logistic regression for intra and tree

### ISSUE THREAD

**Issue by caterinap** [paternogbc/sensiPhy#53]
I have to find a way to ggplot logistic regression with the associated error (due to intra or tree variation). While looking for an acceptable solution I am just going to turn the plot off for intra or tree phyloglm. Otherwise the user will get and ugly thing like this:
![rplot](https://cloud.githubusercontent.com/assets/6351295/9521621/273f9f46-4cd0-11e5-8f9e-e448fb6763c2.jpeg)

**Comment by paternogbc** [comment]
Hey Cat, I was with the same problem. I managed to fix! See issue #48.
![](http://i.imgur.com/DsjmXQn.jpg)

But in your case, each line will be from different slopes and intercepts (based on the standard error, right?)
I fixed based on this answer [link](http://stackoverflow.com/questions/32225223/geom-abline-for-logistic-regression-ggplot2). To do a similar approach, you first need to add a secondary class to the output from tree_phyloglm, at the end of the code:

> class(res) <- c("sensiTree", "sensiTreeL").

Instead of 
> class(res) <- "sensiTree"

Then you can use `if(length(class) == 2)` in your plot function, at the end of ggplot. 
You can have a look at the code from sesi_plot.sensiClade [link](https://github.com/paternogbc/sensiPhy/blob/master/R/plot_clade_phylolm.R)
Remember that you need first to save part of the ggplot into an object, then you can use `if` to add the geom_abline (if from phylolm) or geom_line (if from phyloglm). see stack overflow answer and the code for details.

cheers,
Guga

**Comment by caterinap** [comment]
Oh that is great!!! Thanks!!!!

**Comment by paternogbc** [comment]
nice =) It is a bit tricky.. so if you need help let me know.

Cheers

**Comment by caterinap** [comment]
Worked great!

**Comment by paternogbc** [comment]
Perfect!
