### ISSUE TITLE
summary method for samp_phylm

### ISSUE THREAD

**Issue by paternogbc** [paternogbc/sensiPhy#93]
Include new summary statistics about slope estimation and variance and not only p-values. 
The current method is p-value centered. I think is too poor to report only % of times that p-values were higher than 0.05. We should include some metrics of accuracy for slope and intercept. Not sure which ones.

**Comment by paternogbc** [comment]
Hey @caterinap and @gijsbertwerner,

Any suggestions to address this concerns?
I am a bit unhappy with:
1. the summary output from samp_xxx because it is p-value centered but I have no ideas on how to provide an more stats related to estimates accuracy. 
2. the summary output from intra_xxx and tree_xxx because it is a bit difficult to read essential information. Any ideas how to change the presentation of these stats? Perhaps focusing on model coefficients and their 95% intervals and a second block with the other information (AIC, etc). This will also help to avoid printing the numbers in exp notation.

**Comment by caterinap** [comment]
Yes, could be a first block with mean CI_low, CI_high for intercept, slope and pval and a second block with, all the rest / everything again. I would prefer a second block that maybe is not printed but with everything, because it is easier to export. Would that be fine?

**Comment by caterinap** [comment]
Concerning samp_xxx what about reporting the (mean or min/max?) percentage of change?

**Comment by gijsbertwerner** [comment]
Yes, I see what you mean. The one for samp_xxx particularly is now a bit sparse, and the the one for intra/tree a bit too complex.

I would say for influ/tree to reduce the output a bit. Probably cut the min/max, because we already give 95%-CI which is much more informative. People that really need the min/max can easily get it manually. Even the sd_intra column could could go, if we really want to save space.  And moving aic and optpar to a seperate block would be good, I agree :-)

**Comment by gijsbertwerner** [comment]
With regard to samp_xx why not print the mean and/or median percentage of change, something along the lines of: 

samp$samp.model.estimates %>% group_by(n.percent) %>% summarise(median.intercept.perc=median(intercept.perc),
                                                                mean.intercept.perc=mean(intercept.perc))

This would give people some sense not just of the statistical significance of these replicates, but also of the size. 

Alternatively, we could consider presenting the median/mean (absolute) DF or sDF (if we decide to include sDF here too, see this issue: https://github.com/paternogbc/sensiPhy/issues/108)?

**Comment by gijsbertwerner** [comment]
Ah, I just see that @caterinap had the same suggestion for samp_xxx :-)

**Comment by gijsbertwerner** [comment]
A factor to consider with some of these things is that if in the future we are going to expand our functions to also allow for regression with multiple predictors, we may have to write new summary functions for those more complex regressions, because otherwise we'll soon find that the output becomes overwhelmingly complex. We don't need to worry about this now, but good to think about for a future release..

**Comment by caterinap** [comment]
Ok, I am working on intra and tree summaries following @gijsbertwerner suggestion

**Comment by paternogbc** [comment]
Hahaha, lets use emoticon now to agree with a suggestion.

**Comment by caterinap** [comment]
now summary(my.intra) gives: 
               mean CI_low CI_high
intercept      2.254  1.698   2.810
se.intercept   0.396  0.347   0.444
pval.intercept 0.000  0.000   0.000
slope          0.161  0.124   0.199
se.slope       0.026  0.008   0.045
pval.slope     0.000  0.000   0.000

my.intra$all.stats gives the same output as before

**Comment by paternogbc** [comment]
I am working on summary.samp following @gijsbertwerner suggestions.

**Comment by gijsbertwerner** [comment]
Since I was working on it anyway, I have now implemented this @paternogbc The summary now gives p-values, mean percentage change and mean sDF for intercept and slope. Mean percentage change and mean sDF to some extent give the same information, so if it feels cluttered. We can remove either of these? If we cut one, I guess mean percentage has the advantage that it is easier to interpret for people, but sDF has the advantage that it also gives information about the direction of the effect (negative vs postivie), which is very useful. To me, it doesn't seem too full now. so I would keep both?  

Regardless,  the good thing is that people now won't have to rely on just p-value metrics anymore, but also get a sense of the size of the change :-)

**Comment by paternogbc** [comment]
Perfect @gijsbertwerner.
I liked how it is, thanks =)

**Comment by gijsbertwerner** [comment]
Excellent!
